#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
#
# Bring a copy of libstns into external/, and write down where it came from.
#
# This is the writing half of the arrangement whose reading half is
# tests/check_external.sh.  libstns is not a submodule: a GitHub tag tarball
# does not carry submodule content, so every packaging system this is fed to -
# ports, pkgsrc, Homebrew - would need telling about it, one workaround each.
# A vendored copy makes the tarball self-contained and the port ordinary.
#
# What a submodule did give was a recorded revision, and that is worth keeping,
# so it is kept the way the bundled parsers already record theirs: in
# external/MANIFEST, with a commit and a checksum per file.  "make external"
# then answers both questions a submodule answered - has anybody edited the
# copy, and has upstream moved on - without anybody having to clone anything.
#
#	make vendor			from ../libstns
#	make vendor LIBSTNS=/path/to/libstns
#
# It refuses to copy from a dirty checkout.  The point of the manifest is that
# the copy is one particular commit of libstns; vendoring uncommitted work
# would record a commit the files do not correspond to, which is worse than
# recording nothing at all.

set -eu

SRCDIR=$(cd "$(dirname "$0")/.." && pwd)
LIBSTNS=${1:-$SRCDIR/../libstns}

[ -d "$LIBSTNS/src" ] || {
	echo "$0: no libstns checkout at $LIBSTNS" >&2
	echo "usage: $0 [path to a libstns checkout]" >&2
	exit 1
}
LIBSTNS=$(cd "$LIBSTNS" && pwd)

sha256_of() {
	if command -v sha256 >/dev/null 2>&1; then
		sha256 -q "$1"
	elif command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | cut -d' ' -f1
	else
		shasum -a 256 "$1" | cut -d' ' -f1
	fi
}

# The revision being recorded, which has to be a real one.
if [ -n "$(git -C "$LIBSTNS" status --porcelain 2>/dev/null)" ]; then
	echo "$0: $LIBSTNS has uncommitted changes" >&2
	echo "  The manifest records a commit and a checksum per file, so the" >&2
	echo "  files have to be that commit.  Commit libstns first." >&2
	exit 1
fi
commit=$(git -C "$LIBSTNS" rev-parse HEAD)
date=$(git -C "$LIBSTNS" show -s --format=%cs HEAD)
repo=zakinko/libstns

DEST=$SRCDIR/external/bsd/libstns

echo "== copying libstns@$(echo "$commit" | cut -c1-12) =="

rm -rf "$DEST"
mkdir -p "$DEST/src" "$DEST/man" "$DEST/tests"

# The layout upstream uses is kept, so that a manifest path is the upstream
# path with one prefix in front of it and a reader can see that at a glance.
#
#   src/		the library, compiled straight into this program
#   man/		stns-key-wrapper(8), whose program is built from src/
#   tests/		the mock API server the integration tests run against
for f in "$LIBSTNS"/src/*.c "$LIBSTNS"/src/*.h; do
	cp "$f" "$DEST/src/"
done
cp "$LIBSTNS/man/stns-key-wrapper.8" "$DEST/man/"
cp "$LIBSTNS/tests/mock_stns_server.py" "$DEST/tests/"

# The parsers come along at the path they already had.  They are recorded
# against their own upstreams rather than against libstns, because that is
# where they are actually from - libstns bundles them on exactly these terms,
# and copying the entries through keeps the two manifests saying the same
# thing about them.
mkdir -p "$SRCDIR/external/mit"
rm -rf "$SRCDIR/external/mit/parson" "$SRCDIR/external/mit/tomlc99"
cp -R "$LIBSTNS/external/mit/parson" "$SRCDIR/external/mit/parson"
cp -R "$LIBSTNS/external/mit/tomlc99" "$SRCDIR/external/mit/tomlc99"
rm -f "$SRCDIR"/external/mit/*/*.o

MANIFEST=$SRCDIR/external/MANIFEST
cat >"$MANIFEST" <<'EOF'
# Where the code under external/ came from, and exactly which upstream
# revision it is.
#
# NetBSD records this in the CVS import tag; git has no equivalent, so it is
# written down here instead.  tests/check_external.sh reads this file to check
# two separate things: that the bundled copies still match these checksums, so
# a local edit cannot creep in unnoticed, and that the recorded revision is
# still upstream's current one, so a bundled copy cannot quietly rot.
#
# Nothing here is modified from upstream.  The directory a component sits in
# is named for its licence.
#
# Generated by tests/vendor_libstns.sh; edit that, not this.
#
#   component <name> <github repo> <commit> <date>
#   file      <sha256> <path relative to external/> [<path in that repo>]
#
# The last field is only needed for a component vendored from a subdirectory
# of its repository, which cannot be found by basename alone.

EOF

printf 'component libstns %s %s %s\n' "$repo" "$commit" "$date" >>"$MANIFEST"
(cd "$DEST" && find src man tests -type f | sort) | while read -r rel; do
	printf 'file      %s bsd/libstns/%s %s\n' \
	    "$(sha256_of "$DEST/$rel")" "$rel" "$rel" >>"$MANIFEST"
done

# Everything from "component parson" onwards in libstns's own manifest, which
# is the parsers and nothing else.
echo >>"$MANIFEST"
sed -n '/^component parson/,$p' "$LIBSTNS/external/MANIFEST" >>"$MANIFEST"

echo "== external/MANIFEST =="
grep '^component' "$MANIFEST"
echo
echo "now run: make external"
